// dummyNotes.js

export const groupMeta = {
  1: { groupName: "Design Notes", groupColor: "#FFB6B9" },
  2: { groupName: "Life Plans", groupColor: "#A0E7E5" },
  3: { groupName: "Wellness", groupColor: "#B4F8C8" },
};

export const dummyNotes = [
  {
    noteID: 25,
    title: "Marketing Ideas",
    description: "Brainstorming new campaigns for Q4:\n- Social media contests\n- Collaborate with influencers\n- Launch holiday email series",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#FFD580",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 24,
    title: "Meditation Routine",
    description: "Morning meditation:\n- 5 min deep breathing\n- 10 min mindfulness\n- Journaling thoughts afterward",
    isPrivate: false,
    isNotifiable: false,
    noteColor: "#B4F8C8",
    isActive: true,
    groupId: 3,
    groupName: groupMeta[3].groupName,
    groupColor: groupMeta[3].groupColor,
  },
  {
    noteID: 23,
    title: "App UI Inspiration",
    description: "Screens to reference:\n- Dribbble mobile dashboards\n- Figma community templates\n- Use soft gradient backgrounds",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#FFB6B9",
    isActive: true,
    groupId: 1,
    groupName: groupMeta[1].groupName,
    groupColor: groupMeta[1].groupColor,
  },
  {
    noteID: 22,
    title: "Weekly Groceries",
    description: "Vegetables, fruits, bread, milk, eggs, cheese, yogurt, snacks, pasta, rice",
    isPrivate: true,
    isNotifiable: false,
    noteColor: "#C1F4C5",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 21,
    title: "Workout Routine",
    description: "Mon: Chest\nTue: Back\nWed: Legs\nThu: Shoulders\nFri: Core\nSat: Cardio\nSun: Rest",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#AEDFF7",
    isActive: true,
    groupId: 3,
    groupName: groupMeta[3].groupName,
    groupColor: groupMeta[3].groupColor,
  },
  {
    noteID: 20,
    title: "Project Meeting Notes",
    description: "Discussed:\n- Sprint tasks\n- Client feedback\n- Deadline adjustments\nNext meeting: Friday 10 AM",
    isPrivate: true,
    isNotifiable: true,
    noteColor: "#D4A5A5",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 19,
    title: "Travel Checklist",
    description: "Passport, tickets, charger, toiletries, clothes, sunglasses, water bottle, travel pillow",
    isPrivate: false,
    isNotifiable: false,
    noteColor: "#CDEAC0",
    isActive: true,
    groupId: 2,
    groupName: groupMeta[2].groupName,
    groupColor: groupMeta[2].groupColor,
  },
  {
    noteID: 18,
    title: "Reading List",
    description: "Atomic Habits, Deep Work, The Psychology of Money, The Midnight Library, Educated",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#FFDE7D",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 17,
    title: "Daily Journal",
    description: "Morning reflection: Gratitude, priorities, affirmations. Evening reflection: Wins, lessons learned",
    isPrivate: true,
    isNotifiable: false,
    noteColor: "#F3D1F4",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 16,
    title: "Client Feedback",
    description: "Client requests:\n- Update homepage banner\n- Change color scheme\n- Add testimonial section",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#FFC3A0",
    isActive: true,
    groupId: 1,
    groupName: groupMeta[1].groupName,
    groupColor: groupMeta[1].groupColor,
  },
  {
    noteID: 15,
    title: "Job Applications",
    description: "Companies applied to this week:\n- Google\n- Stripe\n- Notion\nUpdated LinkedIn and cover letters",
    isPrivate: true,
    isNotifiable: true,
    noteColor: "#FFC3A0",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 14,
    title: "UI Design Ideas",
    description: "New app redesign:\n- Neumorphism depth\n- Soft gradients\n- Reanimated animations\n- Feather icons",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#CDEAC0",
    isActive: true,
    groupId: 1,
    groupName: groupMeta[1].groupName,
    groupColor: groupMeta[1].groupColor,
  },
  {
    noteID: 13,
    title: "Weekend Plans",
    description: "Watch Interstellar, deep clean kitchen, grocery shopping, visit grandma, blog draft, meal prep",
    isPrivate: false,
    isNotifiable: false,
    noteColor: "#FFDAC1",
    isActive: true,
    groupId: 2,
    groupName: groupMeta[2].groupName,
    groupColor: groupMeta[2].groupColor,
  },
  {
    noteID: 12,
    title: "Daily Gratitude",
    description: "Grateful for friends, health, breakfast, morning walk, learning. Write 3 things each night",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#A0E7E5",
    isActive: true,
    groupId: 3,
    groupName: groupMeta[3].groupName,
    groupColor: groupMeta[3].groupColor,
  },
  {
    noteID: 11,
    title: "Quotes to Remember",
    description: "“Progress, not perfection.”\n“Discipline is freedom.”\n“The best way out is always through.”",
    isPrivate: false,
    isNotifiable: false,
    noteColor: "#FBE7C6",
    isActive: true,
    groupId: 1,
    groupName: groupMeta[1].groupName,
    groupColor: groupMeta[1].groupColor,
  },
  {
    noteID: 10,
    title: "Budget Plan",
    description: "Rent $1200, Utilities $150, Internet $80, Groceries $350, Transportation $100, Savings $500",
    isPrivate: true,
    isNotifiable: true,
    noteColor: "#B5EAD7",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 9,
    title: "Fitness Progress",
    description: "Week 1: Lost 1.5kg, Week 2: Improved endurance, Week 3: No junk food for 5 days",
    isPrivate: true,
    isNotifiable: false,
    noteColor: "#F3D1F4",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 8,
    title: "Learning Goals",
    description: "React Native crash course, first app, Figma basics, practice algorithms, start blogs",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#C1F4C5",
    isActive: true,
    groupId: 2,
    groupName: groupMeta[2].groupName,
    groupColor: groupMeta[2].groupColor,
  },
  {
    noteID: 7,
    title: "Birthday Gift Ideas",
    description: "Personalized mug, Book: 'The Book Thief', Wall poster set, DIY skincare hamper",
    isPrivate: true,
    isNotifiable: false,
    noteColor: "#FFABAB",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 6,
    title: "Shopping List",
    description: "T-shirts, Jeans, Sneakers, Coffee beans, Shampoo, Dish soap, Fruits, Veggies",
    isPrivate: false,
    isNotifiable: false,
    noteColor: "#E0BBE4",
    isActive: true,
    groupId: 3,
    groupName: groupMeta[3].groupName,
    groupColor: groupMeta[3].groupColor,
  },
  {
    noteID: 5,
    title: "Project Roadmap",
    description: "Q4 2025 Roadmap: research, design system, start sprint Oct 1, internal testing, beta release",
    isPrivate: true,
    isNotifiable: true,
    noteColor: "#D4A5A5",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 4,
    title: "Recipe: Pancakes",
    description: "1 cup flour, 2 tbsp sugar, 1 tbsp baking powder, 1/2 tsp salt, 1 egg, 1 cup milk, 2 tbsp butter",
    isPrivate: false,
    isNotifiable: false,
    noteColor: "#B0E57C",
    isActive: true,
    groupId: 1,
    groupName: groupMeta[1].groupName,
    groupColor: groupMeta[1].groupColor,
  },
  {
    noteID: 3,
    title: "Vacation Checklist",
    description: "Passport, Boarding pass, Sunscreen, Sunglasses, Travel pillow, Cables, Clothes, Toiletries",
    isPrivate: true,
    isNotifiable: true,
    noteColor: "#FFD580",
    isActive: true,
    groupId: null,
  },
  {
    noteID: 2,
    title: "Book Recommendations",
    description: "Atomic Habits, Deep Work, The Midnight Library, Can’t Hurt Me, Educated, Psychology of Money",
    isPrivate: false,
    isNotifiable: false,
    noteColor: "#AEDFF7",
    isActive: true,
    groupId: 2,
    groupName: groupMeta[2].groupName,
    groupColor: groupMeta[2].groupColor,
  },
  {
    noteID: 1,
    title: "Workout Plan",
    description: "Monday: Chest, Tuesday: Back, Wednesday: Cardio, Thursday: Legs, Friday: Yoga, Weekend: Outdoor activities",
    isPrivate: false,
    isNotifiable: true,
    noteColor: "#FFB6C1",
    isActive: true,
    groupId: 3,
    groupName: groupMeta[3].groupName,
    groupColor: groupMeta[3].groupColor,
  },
];
